# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\principal_motorista.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TelaPrincipalMotorista(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.b_cad_rota = QtWidgets.QPushButton(self.frame)
        self.b_cad_rota.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\../Icons/feather/chevrons-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_cad_rota.setIcon(icon)
        self.b_cad_rota.setObjectName("b_cad_rota")
        self.verticalLayout.addWidget(self.b_cad_rota)
        self.b_cad_carro = QtWidgets.QPushButton(self.frame)
        self.b_cad_carro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\../Icons/feather/truck.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_cad_carro.setIcon(icon1)
        self.b_cad_carro.setObjectName("b_cad_carro")
        self.verticalLayout.addWidget(self.b_cad_carro)
        self.b_chat = QtWidgets.QPushButton(self.frame)
        self.b_chat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui\\../Icons/feather/users.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_chat.setIcon(icon2)
        self.b_chat.setObjectName("b_chat")
        self.verticalLayout.addWidget(self.b_chat)
        self.b_voltar = QtWidgets.QPushButton(self.frame)
        self.b_voltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_voltar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ui\\../Icons/feather/arrow-left-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_voltar.setIcon(icon3)
        self.b_voltar.setIconSize(QtCore.QSize(30, 30))
        self.b_voltar.setObjectName("b_voltar")
        self.verticalLayout.addWidget(self.b_voltar, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.frame, 0, 0, 3, 1)
        self.b_perfil = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_perfil.sizePolicy().hasHeightForWidth())
        self.b_perfil.setSizePolicy(sizePolicy)
        self.b_perfil.setMinimumSize(QtCore.QSize(90, 28))
        self.b_perfil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.b_perfil.setStyleSheet("QPushButton { \n"
"    \n"
"     border: none;\n"
" }")
        self.b_perfil.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ui\\../Icons/feather/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_perfil.setIcon(icon4)
        self.b_perfil.setIconSize(QtCore.QSize(30, 30))
        self.b_perfil.setObjectName("b_perfil")
        self.gridLayout.addWidget(self.b_perfil, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMouseTracking(False)
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 534, 494))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout.addWidget(self.frame_2, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_cad_rota.setText(_translate("MainWindow", "Cadastro de Rotas"))
        self.b_cad_carro.setText(_translate("MainWindow", "Cadastro de carro"))
        self.b_chat.setText(_translate("MainWindow", "Chat"))
        self.b_voltar.setToolTip(_translate("MainWindow", "Voltar"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Route Run - </span><span style=\" font-size:20pt; font-weight:600; font-style:italic;\">Motorista</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = TelaPrincipalMotorista()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
