# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class TelaInicial(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_3.setFont(font)
        self.label_3.setMidLineWidth(0)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditMail = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMail.setObjectName("lineEditMail")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditMail)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditSenha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSenha.setObjectName("lineEditSenha")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditSenha)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonSair = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSair.setObjectName("pushButtonSair")
        self.horizontalLayout.addWidget(self.pushButtonSair)
        self.pushButtonEntrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEntrar.setObjectName("pushButtonEntrar")
        self.horizontalLayout.addWidget(self.pushButtonEntrar)
        self.pushButtonCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCadastrar.setObjectName("pushButtonCadastrar")
        self.horizontalLayout.addWidget(self.pushButtonCadastrar)
        self.pushButtonRedefinir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRedefinir.setObjectName("pushButtonRedefinir")
        self.horizontalLayout.addWidget(self.pushButtonRedefinir)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.verticalLayout.addLayout(self.formLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditMail, self.lineEditSenha)
        MainWindow.setTabOrder(self.lineEditSenha, self.pushButtonSair)
        MainWindow.setTabOrder(self.pushButtonSair, self.pushButtonEntrar)
        MainWindow.setTabOrder(self.pushButtonEntrar, self.pushButtonCadastrar)
        MainWindow.setTabOrder(self.pushButtonCadastrar, self.pushButtonRedefinir)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Route Run"))
        self.label.setText(_translate("MainWindow", "e-mail:"))
        self.label_2.setText(_translate("MainWindow", "Senha:"))
        self.pushButtonSair.setText(_translate("MainWindow", "Sair"))
        self.pushButtonEntrar.setText(_translate("MainWindow", "Entrar"))
        self.pushButtonCadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.pushButtonRedefinir.setText(_translate("MainWindow", "Redefinir senha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = TelaInicial()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
